#!/usr/bin/env python

import os, re

buildme = not bld.env.TOOLS_DISABLED and not bld.env.EXAMPLES_DISABLED
builduis = bld.env.BUILD_EXAMPLE_UIS

if buildme:
	examples = [ "volume" ]
	first_plugin = True

	bundle = 'lvtk.lv2'
	install_dir = os.path.join (bld.env.LV2DIR, bundle)
	module_pat = re.sub('^lib', '', bld.env.cxxshlib_PATTERN)
	module_ext = module_pat[module_pat.rfind('.'):]
	plugin_env = bld.env.derive()
	plugin_env.cxxshlib_PATTERN = module_pat

	for slug in examples:
		if first_plugin:
			first_plugin = False
			bld (
				features	= 'subst',
				source		= 'manifest.ttl.in',
				target		= '%s/manifest.ttl' % bundle,
				LIB_EXT		= module_ext,
				install_path = install_dir
			)

		bld (
			features	= 'subst',
			source		= '%s.ttl' % slug,
			target		= '%s/%s.ttl' % (bundle, slug),
			install_path = install_dir
		)

		plugin = bld.shlib (
			name          = slug,
			target        = '%s/%s' % (bundle, slug),
			source        = "%s.cpp" % slug,
			includes      = [],
			use           = [ 'LV2' ],
			install_path  = install_dir,
			env			  = plugin_env
		)
