#!/usr/bin/env python

''' This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public Licence as published by
the Free Software Foundation, either version 3 of the Licence, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
file COPYING for more details. '''

import os, re

buildme = not bld.env.TOOLS_DISABLED and not bld.env.EXAMPLES_DISABLED
builduis = bld.env.BUILD_EXAMPLE_UIS

if buildme:
	examples = [ "silence", "workhorse" ] #, "beep", "volume" ]
	first_plugin = True

	bundle = 'lvtk-examples.lv2'
	install_dir = os.path.join (bld.env.LV2DIR, bundle)
	module_pat = re.sub('^lib', '', bld.env.cxxshlib_PATTERN)
	module_ext = module_pat[module_pat.rfind('.'):]
	plugin_env = bld.env.derive()
	plugin_env.cxxshlib_PATTERN = module_pat

	for slug in examples:
		if first_plugin:
			first_plugin = False
			bld (
				features	= 'subst',
				source		= 'manifest.ttl.in',
				target		= '%s/manifest.ttl' % bundle,
				LIB_EXT		= module_ext,
				install_path = install_dir
			)

		bld (
			features	= 'subst',
			source		= '%s.ttl' % slug,
			target		= '%s/%s.ttl' % (bundle, slug),
			install_path = install_dir
		)

		plugin = bld.shlib (
			cxxflags      = '-std=c++14',
			name          = slug,
			target        = '%s/%s' % (bundle, slug),
			source        = "%s.cpp" % slug,
			includes      = [],
			use           = bld.env.LIB_LVTK_PLUGIN,
			install_path  = install_dir,
			env			  = plugin_env
		)

		# Build the plugin gui (if able)
		uislug = slug + "_ui"
		uisrc  = uislug + ".cpp"

		if builduis and bld.path.find_resource(uisrc):
			ui = bld.shlib (
				name          = uislug,
				target        = '%s/%s' % (bundle, uislug),
				source        = uisrc,
				cxxflags      = ['-Wl,-z,nodelete'],
				includes      = ["../build/examples"],
				use           = [ bld.env.LIB_LVTK_UI, "gtkmm" ],
				LIB_EXT		  = bld.env.pluginlib_EXT
			)
