#!/usr/bin/env python

''' This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public Licence as published by
the Free Software Foundation, either version 3 of the Licence, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
file COPYING for more details. '''

buildme = not bld.env.TOOLS_DISABLED

if buildme:
	bld.program(
		source = "ttl2c.cpp",
		target = "ttl2c",
		name   = "ttl2c",
		use    = "redland"
)
