#!/usr/bin/env python

''' This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public Licence as published by
the Free Software Foundation, either version 3 of the Licence, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
file COPYING for more details. '''

pkg=bld.env.APPNAME

plugin_code = bld.path.ant_glob("*plugin*.cpp")
gtkui_code  = bld.path.ant_glob("ui.cpp")

# Build the support library - Not Available yet

# Build the plugin library
bld.stlib(
	source   = plugin_code,
	includes = ["../lvtk", "include"],
	cxxflags = ["-fPIC"],
	target   = bld.env.LIB_LVTK_PLUGIN,
	name     = bld.env.LIB_LVTK_PLUGIN
)

# Build the GtkUI library
if not bld.env.UI_DISABLED:
	bld.stlib(
		source   = gtkui_code,
		includes = ["../lvtk", "include"],
		cxxflags = ["-fPIC"],
		target   = bld.env.LIB_LVTK_UI,
		name     = bld.env.LIB_LVTK_UI,
	)
