#!/usr/bin/env python

''' This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public Licence as published by
the Free Software Foundation, either version 3 of the Licence, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
file COPYING for more details. '''

pkg=bld.env.APPNAME

plugin_code = bld.path.ant_glob("*plugin*.cpp")
gtkui_code  = bld.path.ant_glob("*gtkui*.cpp")

bld.stlib(
	source   = plugin_code,
	includes = ["../daps", "include"],
	cxxflags = ["-fPIC"],
	target   = bld.env.LIB_DAPS,
	name     = bld.env.LIB_DAPS
)

if not bld.env.UI_DISABLED:
	bld.stlib(
		source   = gtkui_code,
		includes = ["../daps", "include"],
		cxxflags = ["-fPIC"],
		target   = bld.env.LIB_DAPS_GTKUI,
		name     = bld.env.LIB_DAPS_GTKUI,
		use      = "gtkmm"
	)

