name: Build and Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: System Packages
      run: apt-get update && apt install graphviz doxygen python3-sphinx python3-sphinx-rtd-theme
    - name: Setup
      run: meson setup -Ddoc=enabled -Dtest=enabled build
    - name: Compile
      run: meson compile -C build
    - name: Test
      run: meson test -C build
